### ISSUE TITLE
Site needs "Space Mono" font

### ISSUE THREAD

**Issue by briancrogers** [cooltexts/cooltexts.github.io#1]
Drop this into the head element to enable the cool font:
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Space Mono">
```

**Comment by cooltexts** [comment]
thank you, you are such a savior! fixed it now in [d9d0485](https://github.com/cooltexts/cooltexts.github.io/commit/d9d0485c8da9a3abcd9acc90f01b02751da3adb2)
